// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApGKvUSxZUUlc78RAriOlChsRda8tdTFs',
    appId: '1:1053199896036:web:d2cbc28acd07ef757d8bf1',
    messagingSenderId: '1053199896036',
    projectId: 'bazaar-7eaad',
    authDomain: 'bazaar-7eaad.firebaseapp.com',
    storageBucket: 'bazaar-7eaad.appspot.com',
    measurementId: 'G-3KR30H49NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBwCUrShHS0BSD83gOvBcTwsbKy-dxvWQ',
    appId: '1:1053199896036:android:4ebebfa40c831b397d8bf1',
    messagingSenderId: '1053199896036',
    projectId: 'bazaar-7eaad',
    storageBucket: 'bazaar-7eaad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeoS5kuI1fnsvFlQHGiUByYFOzL8-RjVU',
    appId: '1:1053199896036:ios:a1813e46d47624dc7d8bf1',
    messagingSenderId: '1053199896036',
    projectId: 'bazaar-7eaad',
    storageBucket: 'bazaar-7eaad.appspot.com',
    androidClientId:
        '1053199896036-eovjl0dpndak7d4mpmefiqign1ueol4m.apps.googleusercontent.com',
    iosClientId:
        '1053199896036-2prmas5c1pejvq4ib29miqsgp9c1jr3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bazaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeoS5kuI1fnsvFlQHGiUByYFOzL8-RjVU',
    appId: '1:1053199896036:ios:a1813e46d47624dc7d8bf1',
    messagingSenderId: '1053199896036',
    projectId: 'bazaar-7eaad',
    storageBucket: 'bazaar-7eaad.appspot.com',
    androidClientId:
        '1053199896036-eovjl0dpndak7d4mpmefiqign1ueol4m.apps.googleusercontent.com',
    iosClientId:
        '1053199896036-2prmas5c1pejvq4ib29miqsgp9c1jr3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bazaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApGKvUSxZUUlc78RAriOlChsRda8tdTFs',
    appId: '1:1053199896036:web:3c73bb95fdf731fe7d8bf1',
    messagingSenderId: '1053199896036',
    projectId: 'bazaar-7eaad',
    authDomain: 'bazaar-7eaad.firebaseapp.com',
    storageBucket: 'bazaar-7eaad.appspot.com',
    measurementId: 'G-792KCP6YV2',
  );
}
